### ISSUE TITLE
Release and push to PyPi

### ISSUE THREAD

**Issue by tsalo** [bids-standard/pybids-reports#17]
I'm primarily opening this so it's easier to keep track of the `pybids-reports` release in https://github.com/bids-standard/pybids/pull/814.

**Comment by Remi-Gau** [comment]
I think I will go ahead and make a release on pypi to get the ball moving on this one.

**Comment by Remi-Gau** [comment]
note that it may be necessary to do upgrade
pkginfo>=1.10.0 to build

https://github.com/pypa/packaging-problems/issues/735

**Comment by Remi-Gau** [comment]
Done

https://github.com/bids-standard/pybids-reports/releases/tag/0.1.0
