### ISSUE TITLE
Cannot dynamically import the version in the doc

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/pybids-reports#29]
fix the way the version of the subpackage is found.

_Originally posted by @Remi-Gau in https://github.com/bids-standard/pybids-reports/pull/19#discussion_r1210151339_
            

I suspect something related to "packaging".

**Comment by tsalo** [comment]
I tried the following on my branch from #60:

```python
from bids.ext import reports

print(reports.__version__)
```

and it worked:

> '0.1.dev162+g8802b09.d20240123'
