### ISSUE TITLE
Add documentation and build to GitHub Pages

### ISSUE THREAD

**Issue by tsalo** [bids-standard/pybids-reports#3]
The actual documentation can be taken from the reports section of pybids, but we'll need the Sphinx configuration file as well.

**Comment by Remi-Gau** [comment]
@tsalo did you mean github pages or read the docs?

**Comment by tsalo** [comment]
I don't have a strong preference. I think I said GitHub Pages because that's what pybids uses.

**Comment by Remi-Gau** [comment]
OK I actually went with read the docs just because I like the deploy PR preview feature.

This the barest of doc set up but at least there is a minimal foundation to build on.
